[package]
name = "typst-fmt"
version = "0.1.0"
edition = "2021"
authors = ["Astrale <ash4567@outlook.fr>"]
rust-version = "1.56"
description = "A soon to be formatter for the typst lang"
readme = "README.md"
repository = "https://github.com/astrale-sharp/typst-fmt"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities", "development-tools"]


[dependencies]
regex = "1.7.3"
toml = "0.7.3"
#typst = { git = "https://github.com/typst/typst.git" }
typst = "0.1.0"